import { apiClient } from './api-client';
import type { Maintenance, MaintenanceFilters, MaintenanceInput, MaintenanceListResponse, MaintenanceResponse, MaintenanceVehicle } from '../types/maintenance';
export function getMaintenance(token: string, filters: MaintenanceFilters) { const query = new URLSearchParams(); if (filters.search.trim()) query.set('search', filters.search.trim()); if (filters.status) query.set('status', filters.status); if (filters.priority) query.set('priority', filters.priority); if (filters.type) query.set('type', filters.type); query.set('sort', filters.sort); return apiClient<MaintenanceListResponse>(`/maintenance?${query.toString()}`, { method: 'GET' }, token); }
export async function getMaintenanceVehicles(token: string) { return (await apiClient<{ success: true; data: MaintenanceVehicle[] }>('/maintenance/options/eligible-vehicles', { method: 'GET' }, token)).data; }
export async function createMaintenance(token: string, input: MaintenanceInput) { return (await apiClient<MaintenanceResponse>('/maintenance', { method: 'POST', body: input }, token)).data; }
export async function updateMaintenance(token: string, id: string, input: MaintenanceInput) { return (await apiClient<MaintenanceResponse>(`/maintenance/${id}`, { method: 'PATCH', body: input }, token)).data; }
export async function startMaintenance(token: string, id: string) { return (await apiClient<MaintenanceResponse>(`/maintenance/${id}/start`, { method: 'POST' }, token)).data; }
export async function completeMaintenance(token: string, id: string, input: { cost?: number; odometerAtService?: number; technicianName?: string; serviceProvider?: string; notes?: string }) { return (await apiClient<MaintenanceResponse>(`/maintenance/${id}/complete`, { method: 'POST', body: input }, token)).data; }
export async function cancelMaintenance(token: string, id: string, reason?: string) { return (await apiClient<MaintenanceResponse>(`/maintenance/${id}/cancel`, { method: 'POST', body: { reason } }, token)).data; }
export function toInput(item: Maintenance): MaintenanceInput { return { vehicle: item.vehicle.id, type: item.type, description: item.description, priority: item.priority, scheduledDate: item.scheduledDate?.slice(0, 10), serviceProvider: item.serviceProvider ?? '', technicianName: item.technicianName ?? '', cost: item.cost, notes: item.notes ?? '' }; }
