import mongoose, { isValidObjectId, type ClientSession, type FilterQuery } from 'mongoose';
import { MaintenanceCounterModel, MaintenanceLogModel, maintenancePriorities, maintenanceStatuses, maintenanceTypes, type MaintenanceDocument, type MaintenanceLog } from '../models/maintenance.model.js';
import { VehicleModel } from '../models/vehicle.model.js';
import { HttpError } from '../utils/http-error.js';
import type { MaintenanceInput } from '../validation/maintenance.validation.js';

export type MaintenanceListOptions = { search?: string; status?: string; priority?: string; type?: string; vehicle?: string; from?: string; to?: string; sort?: string; page?: string; limit?: string };
type CompletionInput = { cost?: number; odometerAtService?: number; technicianName?: string; serviceProvider?: string; notes?: string };

export async function listMaintenance(options: MaintenanceListOptions) { const filters = await filtersFor(options); const { page, limit } = pagination(options); const total = await MaintenanceLogModel.countDocuments(filters); const records = await MaintenanceLogModel.find(filters).sort(sortFor(options.sort)).skip((page - 1) * limit).limit(limit).populate('vehicle'); return { data: records.map(response), meta: { total, page, limit, totalPages: Math.max(1, Math.ceil(total / limit)) } }; }
export async function getMaintenance(id: string) { return response(await populated(id)); }
export async function createMaintenance(input: MaintenanceInput, userId: string) { await validateVehicle(input.vehicle); const maintenanceNumber = await nextNumber(); const record = await MaintenanceLogModel.create({ ...input, maintenanceNumber, status: 'Scheduled', createdBy: userId }); return response(await record.populate('vehicle')); }
export async function updateMaintenance(id: string, input: Partial<MaintenanceInput>) { ensureId(id); const record = await MaintenanceLogModel.findById(id); if (!record) throw new HttpError(404, 'Maintenance record not found.'); if (record.status !== 'Scheduled') throw new HttpError(400, 'Only Scheduled maintenance can be edited.'); if (input.vehicle) await validateVehicle(input.vehicle); Object.assign(record, input); await record.save(); return response(await record.populate('vehicle')); }
export async function startMaintenance(id: string) { return atomic(async (session) => { const record = await MaintenanceLogModel.findById(id).session(session); if (!record) throw new HttpError(404, 'Maintenance record not found.'); if (record.status !== 'Scheduled') throw new HttpError(400, 'Only Scheduled maintenance can be started.'); if (await MaintenanceLogModel.exists({ _id: { $ne: record.id }, vehicle: record.vehicle, status: 'Active' }).session(session)) throw new HttpError(409, 'Vehicle is already under active maintenance.'); const vehicle = await VehicleModel.findOneAndUpdate({ _id: record.vehicle, status: 'Available' }, { status: 'In Shop' }, { new: true, session }); if (!vehicle) throw new HttpError(409, 'Vehicle is no longer available to start maintenance.'); record.status = 'Active'; record.startedAt = new Date(); record.odometerAtService ??= vehicle.odometer; await record.save({ session }); return record.id; }, () => startFallback(id)).then(getMaintenance); }
export async function completeMaintenance(id: string, input: CompletionInput) { return atomic(async (session) => completeSession(id, input, session), () => completeFallback(id, input)).then(getMaintenance); }
export async function cancelMaintenance(id: string, reason?: string) { return atomic(async (session) => cancelSession(id, reason, session), () => cancelFallback(id, reason)).then(getMaintenance); }
export async function eligibleVehicles() { const vehicles = await VehicleModel.find({ status: 'Available' }).select('registrationNumber name model type odometer region status'); return vehicles.map((vehicle) => ({ id: vehicle.id, registrationNumber: vehicle.registrationNumber, name: vehicle.name, model: vehicle.model, type: vehicle.type, odometer: vehicle.odometer, region: vehicle.region, status: vehicle.status })); }

async function completeSession(id: string, input: CompletionInput, session: ClientSession) { const record = await MaintenanceLogModel.findById(id).session(session); if (!record) throw new HttpError(404, 'Maintenance record not found.'); if (record.status !== 'Active') throw new HttpError(400, 'Only Active maintenance can be completed.'); const vehicle = await VehicleModel.findById(record.vehicle).session(session); if (!vehicle) throw new HttpError(400, 'Maintenance vehicle must still exist.'); if (vehicle.status !== 'Retired') { const updated = await VehicleModel.findOneAndUpdate({ _id: vehicle.id, status: 'In Shop' }, { status: 'Available' }, { new: true, session }); if (!updated) throw new HttpError(409, 'Vehicle is not in the expected In Shop state.'); } Object.assign(record, input, { status: 'Completed', completedAt: new Date() }); await record.save({ session }); return record.id; }
async function cancelSession(id: string, reason: string | undefined, session: ClientSession) { const record = await MaintenanceLogModel.findById(id).session(session); if (!record) throw new HttpError(404, 'Maintenance record not found.'); if (record.status !== 'Scheduled' && record.status !== 'Active') throw new HttpError(400, 'Only Scheduled or Active maintenance can be cancelled.'); if (record.status === 'Active') { const vehicle = await VehicleModel.findById(record.vehicle).session(session); if (!vehicle) throw new HttpError(400, 'Maintenance vehicle must still exist.'); if (vehicle.status !== 'Retired') { const updated = await VehicleModel.findOneAndUpdate({ _id: vehicle.id, status: 'In Shop' }, { status: 'Available' }, { new: true, session }); if (!updated) throw new HttpError(409, 'Vehicle is not in the expected In Shop state.'); } } record.status = 'Cancelled'; record.cancelledAt = new Date(); record.cancellationReason = reason; await record.save({ session }); return record.id; }
async function startFallback(id: string) { const record = await MaintenanceLogModel.findById(id); if (!record) throw new HttpError(404, 'Maintenance record not found.'); if (record.status !== 'Scheduled') throw new HttpError(400, 'Only Scheduled maintenance can be started.'); if (await MaintenanceLogModel.exists({ _id: { $ne: record.id }, vehicle: record.vehicle, status: 'Active' })) throw new HttpError(409, 'Vehicle is already under active maintenance.'); const vehicle = await VehicleModel.findOneAndUpdate({ _id: record.vehicle, status: 'Available' }, { status: 'In Shop' }, { new: true }); if (!vehicle) throw new HttpError(409, 'Vehicle is no longer available to start maintenance.'); try { const updated = await MaintenanceLogModel.findOneAndUpdate({ _id: id, status: 'Scheduled' }, { status: 'Active', startedAt: new Date(), odometerAtService: record.odometerAtService ?? vehicle.odometer }); if (!updated) throw new HttpError(409, 'Maintenance state changed before it could be started.'); return id; } catch (error) { await VehicleModel.updateOne({ _id: vehicle.id, status: 'In Shop' }, { status: 'Available' }); throw error; } }
async function completeFallback(id: string, input: CompletionInput) { const record = await MaintenanceLogModel.findById(id); if (!record) throw new HttpError(404, 'Maintenance record not found.'); if (record.status !== 'Active') throw new HttpError(400, 'Only Active maintenance can be completed.'); const vehicle = await VehicleModel.findById(record.vehicle); if (!vehicle) throw new HttpError(400, 'Maintenance vehicle must still exist.'); let released = false; try { if (vehicle.status !== 'Retired') { if (!await VehicleModel.findOneAndUpdate({ _id: vehicle.id, status: 'In Shop' }, { status: 'Available' })) throw new HttpError(409, 'Vehicle is not in the expected In Shop state.'); released = true; } if (!await MaintenanceLogModel.findOneAndUpdate({ _id: id, status: 'Active' }, { ...input, status: 'Completed', completedAt: new Date() })) throw new HttpError(409, 'Maintenance state changed before completion.'); return id; } catch (error) { if (released) await VehicleModel.updateOne({ _id: vehicle.id, status: 'Available' }, { status: 'In Shop' }); throw error; } }
async function cancelFallback(id: string, reason?: string) { const record = await MaintenanceLogModel.findById(id); if (!record) throw new HttpError(404, 'Maintenance record not found.'); if (record.status === 'Scheduled') { if (!await MaintenanceLogModel.findOneAndUpdate({ _id: id, status: 'Scheduled' }, { status: 'Cancelled', cancelledAt: new Date(), cancellationReason: reason })) throw new HttpError(409, 'Maintenance state changed before cancellation.'); return id; } if (record.status !== 'Active') throw new HttpError(400, 'Only Scheduled or Active maintenance can be cancelled.'); const vehicle = await VehicleModel.findById(record.vehicle); if (!vehicle) throw new HttpError(400, 'Maintenance vehicle must still exist.'); let released = false; try { if (vehicle.status !== 'Retired') { if (!await VehicleModel.findOneAndUpdate({ _id: vehicle.id, status: 'In Shop' }, { status: 'Available' })) throw new HttpError(409, 'Vehicle is not in the expected In Shop state.'); released = true; } if (!await MaintenanceLogModel.findOneAndUpdate({ _id: id, status: 'Active' }, { status: 'Cancelled', cancelledAt: new Date(), cancellationReason: reason })) throw new HttpError(409, 'Maintenance state changed before cancellation.'); return id; } catch (error) { if (released) await VehicleModel.updateOne({ _id: vehicle.id, status: 'Available' }, { status: 'In Shop' }); throw error; } }
async function validateVehicle(id: string) { const vehicle = await VehicleModel.findById(id); if (!vehicle) throw new HttpError(400, 'Selected vehicle does not exist.'); if (vehicle.status !== 'Available') throw new HttpError(400, 'Selected vehicle is not available for maintenance.'); if (await MaintenanceLogModel.exists({ vehicle: vehicle.id, status: 'Active' })) throw new HttpError(409, 'Vehicle is already under active maintenance.'); return vehicle; }
async function atomic<T>(operation: (session: ClientSession) => Promise<T>, fallback: () => Promise<T>) { const session = await mongoose.startSession(); try { let result: T | undefined; await session.withTransaction(async () => { result = await operation(session); }); return result as T; } catch (error) { if (/Transaction numbers are only allowed|does not support transactions|replica set/i.test(error instanceof Error ? error.message : '')) return fallback(); throw error; } finally { await session.endSession(); } }
async function nextNumber() { const year = new Date().getFullYear(); const counter = await MaintenanceCounterModel.findOneAndUpdate({ _id: `maint-${year}` }, { $inc: { sequence: 1 } }, { new: true, upsert: true, setDefaultsOnInsert: true }); return `MAINT-${year}-${String(counter.sequence).padStart(4, '0')}`; }
async function filtersFor(options: MaintenanceListOptions): Promise<FilterQuery<MaintenanceLog>> { const filters: FilterQuery<MaintenanceLog> = {}; const status = text(options.status), priority = text(options.priority), type = text(options.type); if (status) { if (!maintenanceStatuses.includes(status as (typeof maintenanceStatuses)[number])) throw new HttpError(400, 'status is invalid.'); filters.status = status; } if (priority) { if (!maintenancePriorities.includes(priority as (typeof maintenancePriorities)[number])) throw new HttpError(400, 'priority is invalid.'); filters.priority = priority; } if (type) { if (!maintenanceTypes.includes(type as (typeof maintenanceTypes)[number])) throw new HttpError(400, 'type is invalid.'); filters.type = type; } if (options.vehicle) { ensureId(options.vehicle); filters.vehicle = options.vehicle; } if (options.from || options.to) filters.createdAt = dateRange(options.from, options.to); if (text(options.search)) { const expression = new RegExp(escape(text(options.search)!), 'i'); const vehicles = await VehicleModel.find({ $or: [{ registrationNumber: expression }, { name: expression }] }).select('_id'); filters.$or = [{ maintenanceNumber: expression }, { description: expression }, { technicianName: expression }, { serviceProvider: expression }, { vehicle: { $in: vehicles.map((vehicle) => vehicle.id) } }]; } return filters; }
function response(record: MaintenanceDocument) { return { id: record.id, maintenanceNumber: record.maintenanceNumber, vehicle: vehicleSummary(record.vehicle as unknown), type: record.type, description: record.description, priority: record.priority, status: record.status, scheduledDate: record.scheduledDate, startedAt: record.startedAt, completedAt: record.completedAt, cancelledAt: record.cancelledAt, serviceProvider: record.serviceProvider, technicianName: record.technicianName, cost: record.cost, odometerAtService: record.odometerAtService, notes: record.notes, cancellationReason: record.cancellationReason, createdAt: record.createdAt, updatedAt: record.updatedAt }; }
function vehicleSummary(value: unknown) { if (isRecord(value) && '_id' in value) return { id: String(value._id), registrationNumber: value.registrationNumber, name: value.name, model: value.model, type: value.type, odometer: value.odometer, region: value.region, status: value.status }; return { id: String(value) }; }
async function populated(id: string) { ensureId(id); const record = await MaintenanceLogModel.findById(id).populate('vehicle'); if (!record) throw new HttpError(404, 'Maintenance record not found.'); return record; }
function sortFor(value: string | undefined) { const map: Record<string, Record<string, 1 | -1>> = { newest: { createdAt: -1 }, oldest: { createdAt: 1 }, scheduledDate: { scheduledDate: 1 }, cost: { cost: -1 } }; const sort = text(value) ?? 'newest'; if (!map[sort]) throw new HttpError(400, 'sort is invalid.'); return map[sort]; }
function pagination(options: MaintenanceListOptions) { return { page: number(options.page, 1), limit: number(options.limit, 20, 100) }; }
function number(value: string | undefined, fallback: number, maximum?: number) { if (value === undefined) return fallback; const parsed = Number(value); if (!Number.isInteger(parsed) || parsed < 1 || (maximum && parsed > maximum)) throw new HttpError(400, 'Pagination value is invalid.'); return parsed; }
function dateRange(from?: string, to?: string) { const range: Record<string, Date> = {}; if (from) { const date = new Date(from); if (Number.isNaN(date.getTime())) throw new HttpError(400, 'from is invalid.'); range.$gte = date; } if (to) { const date = new Date(to); if (Number.isNaN(date.getTime())) throw new HttpError(400, 'to is invalid.'); date.setHours(23, 59, 59, 999); range.$lte = date; } return range; }
function ensureId(value: string) { if (!isValidObjectId(value)) throw new HttpError(400, 'Maintenance ID is invalid.'); }
function text(value: string | undefined) { return value?.trim(); }
function escape(value: string) { return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); }
function isRecord(value: unknown): value is Record<string, unknown> { return typeof value === 'object' && value !== null; }
